### ISSUE TITLE
fcitx5-lua requires liblua5.4.so

### ISSUE THREAD

**Issue by marguerite** [fcitx/fcitx5-lua#17]
on openSUSE Tumbleweed, luaaddonloader needs liblua5.4.so to run lua based addons, which is annoying, since liblua5.4.so comes from lua54-devel which is a development package :-(

is there any way to make fcitx5-lua rely on liblua.so.5.4 which belongs to liblua5_4-5?

Thx 

Marguerite

**Comment by wengxt** [comment]
Because it uses dlopen instead of link so you don't see it links to it.

While it is possible to build it with -DUSE_DLOPEN=False to make it link to lua directly, it's not desirable because other addon may use a different versioon of lua (in reality, rime-lua is one of the example) and cause issue later.

**Comment by jcleng** [comment]
启动的时候提示:
```
E2022-06-18 20:31:25.540295 luaaddonloader.cpp:21] Failed to load lua library: liblua.so.5.3: cannot open shared object file: No such file or directory
```
用户配置不生效,而且文字乱码,不知道怎么处理
![](https://i.bmp.ovh/imgs/2022/06/18/32aa2098ed3ab5b9.png)
